/*
Spotify Web API

You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChapterBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChapterBase{}

// ChapterBase struct for ChapterBase
type ChapterBase struct {
	// A URL to a 30 second preview (MP3 format) of the chapter. `null` if not available. 
	AudioPreviewUrl NullableString `json:"audio_preview_url"`
	// A list of the countries in which the chapter can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. 
	AvailableMarkets []string `json:"available_markets,omitempty"`
	// The number of the chapter 
	ChapterNumber int32 `json:"chapter_number"`
	// A description of the chapter. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed. 
	Description string `json:"description"`
	// A description of the chapter. This field may contain HTML tags. 
	HtmlDescription string `json:"html_description"`
	// The chapter length in milliseconds. 
	DurationMs int32 `json:"duration_ms"`
	// Whether or not the chapter has explicit content (true = yes it does; false = no it does not OR unknown). 
	Explicit bool `json:"explicit"`
	// External URLs for this chapter. 
	ExternalUrls ExternalUrlObject `json:"external_urls"`
	// A link to the Web API endpoint providing full details of the chapter. 
	Href string `json:"href"`
	// The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the chapter. 
	Id string `json:"id"`
	// The cover art for the chapter in various sizes, widest first. 
	Images []ImageObject `json:"images"`
	// True if the chapter is playable in the given market. Otherwise false. 
	IsPlayable bool `json:"is_playable"`
	// A list of the languages used in the chapter, identified by their [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639) code. 
	Languages []string `json:"languages"`
	// The name of the chapter. 
	Name string `json:"name"`
	// The date the chapter was first released, for example `\"1981-12-15\"`. Depending on the precision, it might be shown as `\"1981\"` or `\"1981-12\"`. 
	ReleaseDate string `json:"release_date"`
	// The precision with which `release_date` value is known. 
	ReleaseDatePrecision string `json:"release_date_precision"`
	// The user's most recent position in the chapter. Set if the supplied access token is a user token and has the scope 'user-read-playback-position'. 
	ResumePoint *ResumePointObject `json:"resume_point,omitempty"`
	// The object type. 
	Type string `json:"type"`
	// The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the chapter. 
	Uri string `json:"uri"`
	// Included in the response when a content restriction is applied. 
	Restrictions *ChapterRestrictionObject `json:"restrictions,omitempty"`
}

type _ChapterBase ChapterBase

// NewChapterBase instantiates a new ChapterBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChapterBase(audioPreviewUrl NullableString, chapterNumber int32, description string, htmlDescription string, durationMs int32, explicit bool, externalUrls ExternalUrlObject, href string, id string, images []ImageObject, isPlayable bool, languages []string, name string, releaseDate string, releaseDatePrecision string, type_ string, uri string) *ChapterBase {
	this := ChapterBase{}
	this.AudioPreviewUrl = audioPreviewUrl
	this.ChapterNumber = chapterNumber
	this.Description = description
	this.HtmlDescription = htmlDescription
	this.DurationMs = durationMs
	this.Explicit = explicit
	this.ExternalUrls = externalUrls
	this.Href = href
	this.Id = id
	this.Images = images
	this.IsPlayable = isPlayable
	this.Languages = languages
	this.Name = name
	this.ReleaseDate = releaseDate
	this.ReleaseDatePrecision = releaseDatePrecision
	this.Type = type_
	this.Uri = uri
	return &this
}

// NewChapterBaseWithDefaults instantiates a new ChapterBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChapterBaseWithDefaults() *ChapterBase {
	this := ChapterBase{}
	return &this
}

// GetAudioPreviewUrl returns the AudioPreviewUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ChapterBase) GetAudioPreviewUrl() string {
	if o == nil || o.AudioPreviewUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.AudioPreviewUrl.Get()
}

// GetAudioPreviewUrlOk returns a tuple with the AudioPreviewUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChapterBase) GetAudioPreviewUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AudioPreviewUrl.Get(), o.AudioPreviewUrl.IsSet()
}

// SetAudioPreviewUrl sets field value
func (o *ChapterBase) SetAudioPreviewUrl(v string) {
	o.AudioPreviewUrl.Set(&v)
}

// GetAvailableMarkets returns the AvailableMarkets field value if set, zero value otherwise.
func (o *ChapterBase) GetAvailableMarkets() []string {
	if o == nil || IsNil(o.AvailableMarkets) {
		var ret []string
		return ret
	}
	return o.AvailableMarkets
}

// GetAvailableMarketsOk returns a tuple with the AvailableMarkets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetAvailableMarketsOk() ([]string, bool) {
	if o == nil || IsNil(o.AvailableMarkets) {
		return nil, false
	}
	return o.AvailableMarkets, true
}

// HasAvailableMarkets returns a boolean if a field has been set.
func (o *ChapterBase) HasAvailableMarkets() bool {
	if o != nil && !IsNil(o.AvailableMarkets) {
		return true
	}

	return false
}

// SetAvailableMarkets gets a reference to the given []string and assigns it to the AvailableMarkets field.
func (o *ChapterBase) SetAvailableMarkets(v []string) {
	o.AvailableMarkets = v
}

// GetChapterNumber returns the ChapterNumber field value
func (o *ChapterBase) GetChapterNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChapterNumber
}

// GetChapterNumberOk returns a tuple with the ChapterNumber field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetChapterNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChapterNumber, true
}

// SetChapterNumber sets field value
func (o *ChapterBase) SetChapterNumber(v int32) {
	o.ChapterNumber = v
}

// GetDescription returns the Description field value
func (o *ChapterBase) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ChapterBase) SetDescription(v string) {
	o.Description = v
}

// GetHtmlDescription returns the HtmlDescription field value
func (o *ChapterBase) GetHtmlDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HtmlDescription
}

// GetHtmlDescriptionOk returns a tuple with the HtmlDescription field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetHtmlDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HtmlDescription, true
}

// SetHtmlDescription sets field value
func (o *ChapterBase) SetHtmlDescription(v string) {
	o.HtmlDescription = v
}

// GetDurationMs returns the DurationMs field value
func (o *ChapterBase) GetDurationMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationMs, true
}

// SetDurationMs sets field value
func (o *ChapterBase) SetDurationMs(v int32) {
	o.DurationMs = v
}

// GetExplicit returns the Explicit field value
func (o *ChapterBase) GetExplicit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Explicit
}

// GetExplicitOk returns a tuple with the Explicit field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetExplicitOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Explicit, true
}

// SetExplicit sets field value
func (o *ChapterBase) SetExplicit(v bool) {
	o.Explicit = v
}

// GetExternalUrls returns the ExternalUrls field value
func (o *ChapterBase) GetExternalUrls() ExternalUrlObject {
	if o == nil {
		var ret ExternalUrlObject
		return ret
	}

	return o.ExternalUrls
}

// GetExternalUrlsOk returns a tuple with the ExternalUrls field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetExternalUrlsOk() (*ExternalUrlObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalUrls, true
}

// SetExternalUrls sets field value
func (o *ChapterBase) SetExternalUrls(v ExternalUrlObject) {
	o.ExternalUrls = v
}

// GetHref returns the Href field value
func (o *ChapterBase) GetHref() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Href
}

// GetHrefOk returns a tuple with the Href field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Href, true
}

// SetHref sets field value
func (o *ChapterBase) SetHref(v string) {
	o.Href = v
}

// GetId returns the Id field value
func (o *ChapterBase) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChapterBase) SetId(v string) {
	o.Id = v
}

// GetImages returns the Images field value
func (o *ChapterBase) GetImages() []ImageObject {
	if o == nil {
		var ret []ImageObject
		return ret
	}

	return o.Images
}

// GetImagesOk returns a tuple with the Images field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetImagesOk() ([]ImageObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Images, true
}

// SetImages sets field value
func (o *ChapterBase) SetImages(v []ImageObject) {
	o.Images = v
}

// GetIsPlayable returns the IsPlayable field value
func (o *ChapterBase) GetIsPlayable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPlayable
}

// GetIsPlayableOk returns a tuple with the IsPlayable field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetIsPlayableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPlayable, true
}

// SetIsPlayable sets field value
func (o *ChapterBase) SetIsPlayable(v bool) {
	o.IsPlayable = v
}

// GetLanguages returns the Languages field value
func (o *ChapterBase) GetLanguages() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Languages
}

// GetLanguagesOk returns a tuple with the Languages field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetLanguagesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Languages, true
}

// SetLanguages sets field value
func (o *ChapterBase) SetLanguages(v []string) {
	o.Languages = v
}

// GetName returns the Name field value
func (o *ChapterBase) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ChapterBase) SetName(v string) {
	o.Name = v
}

// GetReleaseDate returns the ReleaseDate field value
func (o *ChapterBase) GetReleaseDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleaseDate
}

// GetReleaseDateOk returns a tuple with the ReleaseDate field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetReleaseDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReleaseDate, true
}

// SetReleaseDate sets field value
func (o *ChapterBase) SetReleaseDate(v string) {
	o.ReleaseDate = v
}

// GetReleaseDatePrecision returns the ReleaseDatePrecision field value
func (o *ChapterBase) GetReleaseDatePrecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleaseDatePrecision
}

// GetReleaseDatePrecisionOk returns a tuple with the ReleaseDatePrecision field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetReleaseDatePrecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReleaseDatePrecision, true
}

// SetReleaseDatePrecision sets field value
func (o *ChapterBase) SetReleaseDatePrecision(v string) {
	o.ReleaseDatePrecision = v
}

// GetResumePoint returns the ResumePoint field value if set, zero value otherwise.
func (o *ChapterBase) GetResumePoint() ResumePointObject {
	if o == nil || IsNil(o.ResumePoint) {
		var ret ResumePointObject
		return ret
	}
	return *o.ResumePoint
}

// GetResumePointOk returns a tuple with the ResumePoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetResumePointOk() (*ResumePointObject, bool) {
	if o == nil || IsNil(o.ResumePoint) {
		return nil, false
	}
	return o.ResumePoint, true
}

// HasResumePoint returns a boolean if a field has been set.
func (o *ChapterBase) HasResumePoint() bool {
	if o != nil && !IsNil(o.ResumePoint) {
		return true
	}

	return false
}

// SetResumePoint gets a reference to the given ResumePointObject and assigns it to the ResumePoint field.
func (o *ChapterBase) SetResumePoint(v ResumePointObject) {
	o.ResumePoint = &v
}

// GetType returns the Type field value
func (o *ChapterBase) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ChapterBase) SetType(v string) {
	o.Type = v
}

// GetUri returns the Uri field value
func (o *ChapterBase) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *ChapterBase) SetUri(v string) {
	o.Uri = v
}

// GetRestrictions returns the Restrictions field value if set, zero value otherwise.
func (o *ChapterBase) GetRestrictions() ChapterRestrictionObject {
	if o == nil || IsNil(o.Restrictions) {
		var ret ChapterRestrictionObject
		return ret
	}
	return *o.Restrictions
}

// GetRestrictionsOk returns a tuple with the Restrictions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChapterBase) GetRestrictionsOk() (*ChapterRestrictionObject, bool) {
	if o == nil || IsNil(o.Restrictions) {
		return nil, false
	}
	return o.Restrictions, true
}

// HasRestrictions returns a boolean if a field has been set.
func (o *ChapterBase) HasRestrictions() bool {
	if o != nil && !IsNil(o.Restrictions) {
		return true
	}

	return false
}

// SetRestrictions gets a reference to the given ChapterRestrictionObject and assigns it to the Restrictions field.
func (o *ChapterBase) SetRestrictions(v ChapterRestrictionObject) {
	o.Restrictions = &v
}

func (o ChapterBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChapterBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audio_preview_url"] = o.AudioPreviewUrl.Get()
	if !IsNil(o.AvailableMarkets) {
		toSerialize["available_markets"] = o.AvailableMarkets
	}
	toSerialize["chapter_number"] = o.ChapterNumber
	toSerialize["description"] = o.Description
	toSerialize["html_description"] = o.HtmlDescription
	toSerialize["duration_ms"] = o.DurationMs
	toSerialize["explicit"] = o.Explicit
	toSerialize["external_urls"] = o.ExternalUrls
	toSerialize["href"] = o.Href
	toSerialize["id"] = o.Id
	toSerialize["images"] = o.Images
	toSerialize["is_playable"] = o.IsPlayable
	toSerialize["languages"] = o.Languages
	toSerialize["name"] = o.Name
	toSerialize["release_date"] = o.ReleaseDate
	toSerialize["release_date_precision"] = o.ReleaseDatePrecision
	if !IsNil(o.ResumePoint) {
		toSerialize["resume_point"] = o.ResumePoint
	}
	toSerialize["type"] = o.Type
	toSerialize["uri"] = o.Uri
	if !IsNil(o.Restrictions) {
		toSerialize["restrictions"] = o.Restrictions
	}
	return toSerialize, nil
}

func (o *ChapterBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audio_preview_url",
		"chapter_number",
		"description",
		"html_description",
		"duration_ms",
		"explicit",
		"external_urls",
		"href",
		"id",
		"images",
		"is_playable",
		"languages",
		"name",
		"release_date",
		"release_date_precision",
		"type",
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChapterBase := _ChapterBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChapterBase)

	if err != nil {
		return err
	}

	*o = ChapterBase(varChapterBase)

	return err
}

type NullableChapterBase struct {
	value *ChapterBase
	isSet bool
}

func (v NullableChapterBase) Get() *ChapterBase {
	return v.value
}

func (v *NullableChapterBase) Set(val *ChapterBase) {
	v.value = val
	v.isSet = true
}

func (v NullableChapterBase) IsSet() bool {
	return v.isSet
}

func (v *NullableChapterBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChapterBase(val *ChapterBase) *NullableChapterBase {
	return &NullableChapterBase{value: val, isSet: true}
}

func (v NullableChapterBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChapterBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


