/*
Spotify Web API

You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CurrentlyPlayingContextObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurrentlyPlayingContextObject{}

// CurrentlyPlayingContextObject struct for CurrentlyPlayingContextObject
type CurrentlyPlayingContextObject struct {
	// The device that is currently active. 
	Device *DeviceObject `json:"device,omitempty"`
	// off, track, context
	RepeatState *string `json:"repeat_state,omitempty"`
	// If shuffle is on or off.
	ShuffleState *bool `json:"shuffle_state,omitempty"`
	// A Context Object. Can be `null`.
	Context *ContextObject `json:"context,omitempty"`
	// Unix Millisecond Timestamp when data was fetched.
	Timestamp *int32 `json:"timestamp,omitempty"`
	// Progress into the currently playing track or episode. Can be `null`.
	ProgressMs *int32 `json:"progress_ms,omitempty"`
	// If something is currently playing, return `true`.
	IsPlaying *bool `json:"is_playing,omitempty"`
	Item *QueueObjectCurrentlyPlaying `json:"item,omitempty"`
	// The object type of the currently playing item. Can be one of `track`, `episode`, `ad` or `unknown`. 
	CurrentlyPlayingType *string `json:"currently_playing_type,omitempty"`
	// Allows to update the user interface based on which playback actions are available within the current context. 
	Actions *DisallowsObject `json:"actions,omitempty"`
}

// NewCurrentlyPlayingContextObject instantiates a new CurrentlyPlayingContextObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurrentlyPlayingContextObject() *CurrentlyPlayingContextObject {
	this := CurrentlyPlayingContextObject{}
	return &this
}

// NewCurrentlyPlayingContextObjectWithDefaults instantiates a new CurrentlyPlayingContextObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurrentlyPlayingContextObjectWithDefaults() *CurrentlyPlayingContextObject {
	this := CurrentlyPlayingContextObject{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetDevice() DeviceObject {
	if o == nil || IsNil(o.Device) {
		var ret DeviceObject
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetDeviceOk() (*DeviceObject, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given DeviceObject and assigns it to the Device field.
func (o *CurrentlyPlayingContextObject) SetDevice(v DeviceObject) {
	o.Device = &v
}

// GetRepeatState returns the RepeatState field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetRepeatState() string {
	if o == nil || IsNil(o.RepeatState) {
		var ret string
		return ret
	}
	return *o.RepeatState
}

// GetRepeatStateOk returns a tuple with the RepeatState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetRepeatStateOk() (*string, bool) {
	if o == nil || IsNil(o.RepeatState) {
		return nil, false
	}
	return o.RepeatState, true
}

// HasRepeatState returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasRepeatState() bool {
	if o != nil && !IsNil(o.RepeatState) {
		return true
	}

	return false
}

// SetRepeatState gets a reference to the given string and assigns it to the RepeatState field.
func (o *CurrentlyPlayingContextObject) SetRepeatState(v string) {
	o.RepeatState = &v
}

// GetShuffleState returns the ShuffleState field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetShuffleState() bool {
	if o == nil || IsNil(o.ShuffleState) {
		var ret bool
		return ret
	}
	return *o.ShuffleState
}

// GetShuffleStateOk returns a tuple with the ShuffleState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetShuffleStateOk() (*bool, bool) {
	if o == nil || IsNil(o.ShuffleState) {
		return nil, false
	}
	return o.ShuffleState, true
}

// HasShuffleState returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasShuffleState() bool {
	if o != nil && !IsNil(o.ShuffleState) {
		return true
	}

	return false
}

// SetShuffleState gets a reference to the given bool and assigns it to the ShuffleState field.
func (o *CurrentlyPlayingContextObject) SetShuffleState(v bool) {
	o.ShuffleState = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetContext() ContextObject {
	if o == nil || IsNil(o.Context) {
		var ret ContextObject
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetContextOk() (*ContextObject, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given ContextObject and assigns it to the Context field.
func (o *CurrentlyPlayingContextObject) SetContext(v ContextObject) {
	o.Context = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *CurrentlyPlayingContextObject) SetTimestamp(v int32) {
	o.Timestamp = &v
}

// GetProgressMs returns the ProgressMs field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetProgressMs() int32 {
	if o == nil || IsNil(o.ProgressMs) {
		var ret int32
		return ret
	}
	return *o.ProgressMs
}

// GetProgressMsOk returns a tuple with the ProgressMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetProgressMsOk() (*int32, bool) {
	if o == nil || IsNil(o.ProgressMs) {
		return nil, false
	}
	return o.ProgressMs, true
}

// HasProgressMs returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasProgressMs() bool {
	if o != nil && !IsNil(o.ProgressMs) {
		return true
	}

	return false
}

// SetProgressMs gets a reference to the given int32 and assigns it to the ProgressMs field.
func (o *CurrentlyPlayingContextObject) SetProgressMs(v int32) {
	o.ProgressMs = &v
}

// GetIsPlaying returns the IsPlaying field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetIsPlaying() bool {
	if o == nil || IsNil(o.IsPlaying) {
		var ret bool
		return ret
	}
	return *o.IsPlaying
}

// GetIsPlayingOk returns a tuple with the IsPlaying field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetIsPlayingOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPlaying) {
		return nil, false
	}
	return o.IsPlaying, true
}

// HasIsPlaying returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasIsPlaying() bool {
	if o != nil && !IsNil(o.IsPlaying) {
		return true
	}

	return false
}

// SetIsPlaying gets a reference to the given bool and assigns it to the IsPlaying field.
func (o *CurrentlyPlayingContextObject) SetIsPlaying(v bool) {
	o.IsPlaying = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetItem() QueueObjectCurrentlyPlaying {
	if o == nil || IsNil(o.Item) {
		var ret QueueObjectCurrentlyPlaying
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetItemOk() (*QueueObjectCurrentlyPlaying, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given QueueObjectCurrentlyPlaying and assigns it to the Item field.
func (o *CurrentlyPlayingContextObject) SetItem(v QueueObjectCurrentlyPlaying) {
	o.Item = &v
}

// GetCurrentlyPlayingType returns the CurrentlyPlayingType field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetCurrentlyPlayingType() string {
	if o == nil || IsNil(o.CurrentlyPlayingType) {
		var ret string
		return ret
	}
	return *o.CurrentlyPlayingType
}

// GetCurrentlyPlayingTypeOk returns a tuple with the CurrentlyPlayingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetCurrentlyPlayingTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentlyPlayingType) {
		return nil, false
	}
	return o.CurrentlyPlayingType, true
}

// HasCurrentlyPlayingType returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasCurrentlyPlayingType() bool {
	if o != nil && !IsNil(o.CurrentlyPlayingType) {
		return true
	}

	return false
}

// SetCurrentlyPlayingType gets a reference to the given string and assigns it to the CurrentlyPlayingType field.
func (o *CurrentlyPlayingContextObject) SetCurrentlyPlayingType(v string) {
	o.CurrentlyPlayingType = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *CurrentlyPlayingContextObject) GetActions() DisallowsObject {
	if o == nil || IsNil(o.Actions) {
		var ret DisallowsObject
		return ret
	}
	return *o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentlyPlayingContextObject) GetActionsOk() (*DisallowsObject, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *CurrentlyPlayingContextObject) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given DisallowsObject and assigns it to the Actions field.
func (o *CurrentlyPlayingContextObject) SetActions(v DisallowsObject) {
	o.Actions = &v
}

func (o CurrentlyPlayingContextObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurrentlyPlayingContextObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.RepeatState) {
		toSerialize["repeat_state"] = o.RepeatState
	}
	if !IsNil(o.ShuffleState) {
		toSerialize["shuffle_state"] = o.ShuffleState
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.ProgressMs) {
		toSerialize["progress_ms"] = o.ProgressMs
	}
	if !IsNil(o.IsPlaying) {
		toSerialize["is_playing"] = o.IsPlaying
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	if !IsNil(o.CurrentlyPlayingType) {
		toSerialize["currently_playing_type"] = o.CurrentlyPlayingType
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	return toSerialize, nil
}

type NullableCurrentlyPlayingContextObject struct {
	value *CurrentlyPlayingContextObject
	isSet bool
}

func (v NullableCurrentlyPlayingContextObject) Get() *CurrentlyPlayingContextObject {
	return v.value
}

func (v *NullableCurrentlyPlayingContextObject) Set(val *CurrentlyPlayingContextObject) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrentlyPlayingContextObject) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrentlyPlayingContextObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrentlyPlayingContextObject(val *CurrentlyPlayingContextObject) *NullableCurrentlyPlayingContextObject {
	return &NullableCurrentlyPlayingContextObject{value: val, isSet: true}
}

func (v NullableCurrentlyPlayingContextObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrentlyPlayingContextObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


